name: Rubocop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@93287a1fa82c6ddbb6d8db978df4b0119cd8879f
        with:
          ruby-version: 3.2.0

      - name: Install gems
        run: |
          gem install rubocop -v 1.43.0
          gem install rubocop-minitest -v 0.26.1
          gem install rubocop-performance -v 1.15.2

      - name: Run Rubocop
        run: rubocop --except Metrics
