name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up Ruby
        uses: ruby/setup-ruby@d4526a55538b775af234ba4af27118ed6f8f6677
        with:
          ruby-version: .ruby-version

      # Setup code climate
      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      # Run the tests
      - name: Run Ruby tests
        env:
          CAPTURE_CODE_COVERAGE: true
        run: |
          bundle exec rake test
          ./cc-test-reporter format-coverage -t simplecov -o codeclimate.backend.json coverage/backend/.resultset.json
      # Publish the coverage to CodeClimate
      # - name: Publish code coverage
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      #   env:
      #     GIT_BRANCH: ${GITHUB_REF/refs\/heads\//}
      #     CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      #   run: |
      #     ./cc-test-reporter upload-coverage -i codeclimate.*.json
